name: Backend CI Pipeline
on: 
  workflow_dispatch:
  push:
    paths:
      - 'src/server/backend/**'
    

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      working-directory: src/server/backend
    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: yarn install --dev
        working-directory: ${{ env.working-directory }}
      - name: Run ESLint
        run: eslint .**/*.js
        working-directory: ${{ env.working-directory }}