name: Backend CI Pipeline
on: 
  workflow_dispatch:
  push:
    paths:
      - 'src/server/backend/**'
    

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/server/backend
    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: yarn install --dev
      - name: Run ESLint
        run: eslint .**/*.js