name: Backend CI Pipeline
on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn install --dev
      - name: Run ESLint
        run: eslint .**/*.js